Install other github projects with the friends-of-bash helper; #1

diff --git a/helper/functions b/helper/functions
--- a/helper/functions
+++ b/helper/functions
@@ -8,12 +8,20 @@
 # ------------
 install ()
 {
-    local pathRoot="$1"
+    local       pathRoot="$1"
+    local  gitRepository="$2"
+    local nameRepository=""
 
-    eval "declare -A repositoryValues="$(getRepositoryValues "$pathRoot")
+    if [ "$gitRepository" == "" ]; then
+        eval "declare -A repositoryValues="$(getRepositoryValues "$pathRoot")
+        [ $? -gt 0 ] && (>&2 echo "→ abort") && exit
 
-    local gitRepository="${repositoryValues[git]}"
-    local nameRepository="${repositoryValues[name]}"
+         gitRepository="${repositoryValues[git]}"
+        nameRepository="${repositoryValues[name]}"
+    else
+        nameRepository=$(getRepositoryNameFromGivenRepository "$gitRepository")
+        [ $? -gt 0 ] && (>&2 echo "→ abort") && exit
+    fi
 
     # the global mode needs root credentials
     if [ "$UID" -ne "$ROOT_UID" ]; then
@@ -27,6 +35,7 @@ install ()
 
     # calculate git target paths
     installFolder="$TARGET_FOLDER/$nameRepository"
+      installFile="$installFolder/install"
 
     # install this project to install folder
     if [ ! -d "$installFolder" ]; then
@@ -38,6 +47,12 @@ install ()
         echo "git repository \"$gitRepository\" successfully installed into \"$installFolder\"."
     else
         echo "The target install folder \"$installFolder\" already exists → skip.."
+    fi
+
+    # check for install file, execute it and exit function
+    if [ -f "$installFile" ] && [ -x "$installFile" ]; then
+        $installFile
+        return 0
     fi
 
     # install the global scripts
@@ -99,6 +114,7 @@ update()
     fi
 
     eval "declare -A repositoryValues="$(getRepositoryValues "$pathRoot")
+    [ $? -gt 0 ] && (>&2 echo "→ abort") && exit
 
     local gitRepository="${repositoryValues[git]}"
     local nameRepository="${repositoryValues[name]}"
@@ -167,6 +183,7 @@ status ()
     fi
 
     eval "declare -A repositoryValues="$(getRepositoryValues "$pathRoot")
+    [ $? -gt 0 ] && (>&2 echo "→ abort") && exit
 
     local gitRepository="${repositoryValues[git]}"
     local nameRepository="${repositoryValues[name]}"
@@ -244,6 +261,7 @@ getRepositoryVersion()
     local pathRoot="$1"
 
     eval "declare -A repositoryValues="$(getRepositoryValues "$pathRoot")
+    [ $? -gt 0 ] && (>&2 echo "→ abort") && exit
 
     local gitRepository="${repositoryValues[git]}"
     local nameRepository="${repositoryValues[name]}"
@@ -252,6 +270,23 @@ getRepositoryVersion()
     local localVersion=$(getCurrentTagFromGivenPath "$pathRoot")
 
     echo "$nameRepository/$localVersion"
+}
+
+# ------------
+# Extract the name from the given repository.
+#
+# @author  Björn Hempel <bjoern@hempel.li>
+# @version 1.0 (2017-06-03)
+# ------------
+getRepositoryNameFromGivenRepository()
+{
+    if [[ "$1" =~ ([a-zA-Z0-9._-]+)(.git$) ]]; then
+        echo -n "${BASH_REMATCH[1]}"
+        return 0
+    fi
+
+    >&2 echo "Error: no repository name was found"
+    return 1
 }
 
 # ------------
@@ -264,25 +299,28 @@ getRepositoryValues()
 {
     local pathRoot="$1"
 
+    local  gitRepository=""
+    local nameRepository=""
+
     # try to get the git repository source and the name of that repository
     if [ -f "$pathRoot/.git/config" ]; then
-        gitRepository=$(cat "$pathRoot/.git/config" | grep "url =" | awk '{print $3}')
-        [[ "$gitRepository" =~ ([a-zA-Z0-9._-]+)(.git$) ]] && nameRepository="${BASH_REMATCH[1]}" || nameRepository=""
+         gitRepository=$(cat "$pathRoot/.git/config" | grep "url =" | awk '{print $3}')
+        nameRepository=$(getRepositoryNameFromGivenRepository "$gitRepository")
     else
-        gitRepository=""
+         gitRepository=""
         nameRepository=""
     fi
 
     # check git repository config
     if [ "$gitRepository" == "" ]; then
-        echo "No git repository config found → abort.."
-        exit 1
+        >&2 echo "Error: no git repository config found"
+        return 1
     fi
 
     # check git name
     if [ "$nameRepository" == "" ]; then
-        echo "Not able to extract the name of repository → abort.."
-        exit 1
+        >&2 echo "Error: not able to extract the name of repository"
+        return 2
     fi
 
     declare -A ret=()
